# Generated by Django 4.1.13 on 2024-05-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
